version: '3'
services:

    db:
        image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://www.example.com/my-graph"
            DBA_PASSWORD: "dba"
        volumes:
            - ./data/virtuoso:/data
        ports:
            - "8890:8890"
        networks:
            - sbhWeb

    synbiohub-lab:
        build: .
        image: sbh-l
        ports:
            - 0.0.0.0:7777:7777
        networks:
            - sbhWeb
        working_dir: "/opt/synbiohub-lab"
        depends_on:
            - db

networks:
  sbhWeb:
    driver: bridge
