version: '3'
services:

    db:
        image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://www.example.com/my-graph"
            DBA_PASSWORD: "dba"
        volumes:
            - ./data/virtuoso:/data
        ports:
            - "8890:8890"
            - "1111:1111"
        networks:
            - sbhWeb

    synbiohub-lab:
        image: chrisata/sbh-l:latest
        volumes:
          - ./sbh_data:/opt/synbiohub-lab/data
          - ./config.json:/opt/synbiohub-lab/config.local.json
          - ./attachments:/opt/synbiohub-lab/uploads
          - ./tmp:/tmp
        ports:
            - "0.0.0.0:7777:7777"
        networks:
            - sbhWeb
        working_dir: "/opt/synbiohub-lab"
        depends_on:
            - db

networks:
  sbhWeb:
    driver: bridge
